### PR TITLE
Add a Collapse button for filters #58

### PR DESCRIPTION
**Pull request by dangvu0502**
Instead of adding new button, I add ability to collapse filters when user click search box.

### CODE REVIEW

**Comment by Sanix-Darker** [comment]
Thanks for this Pull Request !
It's Huge 😅 !
Looks like there is a lot of code formating !
- Is it possible to split those commits ? (one for the formating, one for the collapse feature and the last one for the yarn lock).
- And a small gif preview of what you did in the Pull Request description ? 🙏🏾 (i didn't setUp a deployment workflow for each new pull request, but i keep that in mind !)

**Comment by dangvu0502** [comment]
Oh, silly me!!
I add all changes to commit without checking redundants (almost is formatting on save and yarn lock autogenerated).
Now It's difficult to split those changes. Should I create new pull request?
I do not know how to create a gif so i will give you video instead.

https://user-images.githubusercontent.com/57172125/184844594-5226084a-958b-4b06-bfa2-1eda499bff5e.mp4

**Comment by Sanix-Darker** [comment]
In a new Pull Request if possible yes, or reset the commit on this PR and push force new ones !
As you wish !
Thanks for the preview, looks awesome 🔥 !

**Comment by dangvu0502** [comment]
I have updated these changes.
Forgive my dummy mistake on committing.

**Comment by Sanix-Darker** [comment]
Thanks for your changes !
Looks Good to me !

> Forgive my dummy mistake on committing.

Don't worry mate, it's okay 😃 !

**Review by Sanix-Darker — APPROVED** [review]

**Pull request merged**
